/*
 * generated by Xtext 2.11.0
 */
package org.moflon.gt.mosl.pattern.language.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor


/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MOSLPatternUiModule extends AbstractMOSLPatternUiModule {
//	private val controller = new 
}
