package org.moflon.gt.ide.ui.highlighting.utils;

public enum XtextColor {
	RED, BLUE, GREEN, YELLOW, VIOLETT, BLACK, WHITE, LIGHT_RED, DARK_RED, LIGHT_BLUE, DARK_BLUE, LIGHT_GREEN, DARK_GREEN, ORANGE, DARK_ORANGE, GRAY, BROWN, GOLD, MISTY_ROSE, DARK_GOLD, LIGHT_YELLOW, DEFAULT;

	
}
