/*
 * generated by Xtext 2.11.0
 */
package org.moflon.gt.mosl.pattern.language

import org.moflon.gt.mosl.pattern.language.MOSLPatternStandaloneSetupGenerated
/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MOSLPatternStandaloneSetup extends MOSLPatternStandaloneSetupGenerated {

	def static void doSetup() {
		new MOSLPatternStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
