/*
 * generated by Xtext 2.11.0
 */
package org.moflon.gt.mosl.pattern.language


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MOSLPatternRuntimeModule extends AbstractMOSLPatternRuntimeModule {
}
