/*
 * generated by Xtext 2.11.0
 */
package org.moflon.gt.mosl.pattern.language.ide


/**
 * Use this class to register ide components.
 */
class MOSLPatternIdeModule extends AbstractMOSLPatternIdeModule {
}
